### PR TITLE
Fix app descriptor attributes indented with tabulation

### LINKED ISSUE #44: application descriptor fails with attributes indented with tabulation
This fails (using the tabulation character to indent XML attributes):

```xml
<?xml version="1.0" encoding="utf-8" ?>
<application
	xmlns="http://ns.adobe.com/air/application/18.0"
	minimumPatchLevel="0">
	<id>com.example.app</id>
</application>
```

This works (using space to indent the XML attributes):

```xml
<?xml version="1.0" encoding="utf-8" ?>
<application
 xmlns="http://ns.adobe.com/air/application/18.0"
 minimumPatchLevel="0">
	<id>com.example.app</id>
</application>
```

---

Side note: I improved a tiny bit the application descriptor validation, so it returns the detail of the error (incoming PR). It says: `"<id> tag not found"` when it fails in the above case.

### PR DESCRIPTION
**Pull request by j3k0**
Closes #44

### CODE REVIEW

**Comment by marchbold** [comment]
I think this is overkill, it's just the space character that should be removed? I can't see that there is any need for the whitespace detection at the beginning of `xmlns`.

**Comment by j3k0** [comment]
To be totally strict, it's probably better to make sure `xmlns` is a standalone word and not any word that ends with `xmlns`. So I find it better to check for the presence of a separator before it (one less possible bug).

Anyway, hacking into XML with RegExp is generally seen as bad practice.

I can see a few possible bugs with this already:

1. What if some internal fields in the application descriptor are CDATA xml, the xmlns will be removed for them also.
2. Whitespaces are allowed at many places: like if someone likes to put spaces around the = sign,`xmlns = "somevalue"`

For `1`, probably this regexp should check that value contains "http://ns.adobe.com/air/application" too.
For `2`, I could fix it.

But anyway, any option to prevent having doing XML RegExp magic would probably be better. Like, maybe, just remove this and check that the namespace is correct, trigger an error if it isn't.

**Comment by marchbold** [comment]
Yep, a better fix would be to remove the namespace using the XML class, it was only a quick addition to get something out.

**Comment by marchbold** [comment]
Pretty sure this is resolved with the rehandling of the xml using proper namespaces, but could you confirm and then we can close this PR?

**Comment by marchbold** [comment]
This is no longer needed as we handle namespaces for the xml correctly

**Pull request closed without merging**
